# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.11.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.11.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/thosakwe/Source/Compilers/bonobo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/thosakwe/Source/Compilers/bonobo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.11.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.11.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.11.0/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.11.0/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.11.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.11.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	cd /Users/thosakwe/Source/Compilers/bonobo && /usr/local/Cellar/cmake/3.11.0/bin/cpack --config ./CPackSourceConfig.cmake /Users/thosakwe/Source/Compilers/bonobo/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.11.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.11.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	cd /Users/thosakwe/Source/Compilers/bonobo && /usr/local/Cellar/cmake/3.11.0/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Data\" \"Documentation\" \"Header\" \"Library\" \"Runtime\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	cd /Users/thosakwe/Source/Compilers/bonobo && $(CMAKE_COMMAND) -E cmake_progress_start /Users/thosakwe/Source/Compilers/bonobo/CMakeFiles /Users/thosakwe/Source/Compilers/bonobo/bonobo/lib/bvm/src/tcc/CMakeFiles/progress.marks
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f CMakeFiles/Makefile2 bonobo/lib/bvm/src/tcc/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/thosakwe/Source/Compilers/bonobo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f CMakeFiles/Makefile2 bonobo/lib/bvm/src/tcc/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f CMakeFiles/Makefile2 bonobo/lib/bvm/src/tcc/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f CMakeFiles/Makefile2 bonobo/lib/bvm/src/tcc/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
bonobo/lib/bvm/src/tcc/CMakeFiles/tcc.dir/rule:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f CMakeFiles/Makefile2 bonobo/lib/bvm/src/tcc/CMakeFiles/tcc.dir/rule
.PHONY : bonobo/lib/bvm/src/tcc/CMakeFiles/tcc.dir/rule

# Convenience name for target.
tcc: bonobo/lib/bvm/src/tcc/CMakeFiles/tcc.dir/rule

.PHONY : tcc

# fast build rule for target.
tcc/fast:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f bonobo/lib/bvm/src/tcc/CMakeFiles/tcc.dir/build.make bonobo/lib/bvm/src/tcc/CMakeFiles/tcc.dir/build
.PHONY : tcc/fast

# Convenience name for target.
bonobo/lib/bvm/src/tcc/CMakeFiles/tiny_libmaker.dir/rule:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f CMakeFiles/Makefile2 bonobo/lib/bvm/src/tcc/CMakeFiles/tiny_libmaker.dir/rule
.PHONY : bonobo/lib/bvm/src/tcc/CMakeFiles/tiny_libmaker.dir/rule

# Convenience name for target.
tiny_libmaker: bonobo/lib/bvm/src/tcc/CMakeFiles/tiny_libmaker.dir/rule

.PHONY : tiny_libmaker

# fast build rule for target.
tiny_libmaker/fast:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f bonobo/lib/bvm/src/tcc/CMakeFiles/tiny_libmaker.dir/build.make bonobo/lib/bvm/src/tcc/CMakeFiles/tiny_libmaker.dir/build
.PHONY : tiny_libmaker/fast

# Convenience name for target.
bonobo/lib/bvm/src/tcc/CMakeFiles/libtcc1.dir/rule:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f CMakeFiles/Makefile2 bonobo/lib/bvm/src/tcc/CMakeFiles/libtcc1.dir/rule
.PHONY : bonobo/lib/bvm/src/tcc/CMakeFiles/libtcc1.dir/rule

# Convenience name for target.
libtcc1: bonobo/lib/bvm/src/tcc/CMakeFiles/libtcc1.dir/rule

.PHONY : libtcc1

# fast build rule for target.
libtcc1/fast:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f bonobo/lib/bvm/src/tcc/CMakeFiles/libtcc1.dir/build.make bonobo/lib/bvm/src/tcc/CMakeFiles/libtcc1.dir/build
.PHONY : libtcc1/fast

# Convenience name for target.
bonobo/lib/bvm/src/tcc/CMakeFiles/libtcc.dir/rule:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f CMakeFiles/Makefile2 bonobo/lib/bvm/src/tcc/CMakeFiles/libtcc.dir/rule
.PHONY : bonobo/lib/bvm/src/tcc/CMakeFiles/libtcc.dir/rule

# Convenience name for target.
libtcc: bonobo/lib/bvm/src/tcc/CMakeFiles/libtcc.dir/rule

.PHONY : libtcc

# fast build rule for target.
libtcc/fast:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f bonobo/lib/bvm/src/tcc/CMakeFiles/libtcc.dir/build.make bonobo/lib/bvm/src/tcc/CMakeFiles/libtcc.dir/build
.PHONY : libtcc/fast

libtcc.o: libtcc.c.o

.PHONY : libtcc.o

# target to build an object file
libtcc.c.o:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f bonobo/lib/bvm/src/tcc/CMakeFiles/libtcc.dir/build.make bonobo/lib/bvm/src/tcc/CMakeFiles/libtcc.dir/libtcc.c.o
.PHONY : libtcc.c.o

libtcc.i: libtcc.c.i

.PHONY : libtcc.i

# target to preprocess a source file
libtcc.c.i:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f bonobo/lib/bvm/src/tcc/CMakeFiles/libtcc.dir/build.make bonobo/lib/bvm/src/tcc/CMakeFiles/libtcc.dir/libtcc.c.i
.PHONY : libtcc.c.i

libtcc.s: libtcc.c.s

.PHONY : libtcc.s

# target to generate assembly for a file
libtcc.c.s:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f bonobo/lib/bvm/src/tcc/CMakeFiles/libtcc.dir/build.make bonobo/lib/bvm/src/tcc/CMakeFiles/libtcc.dir/libtcc.c.s
.PHONY : libtcc.c.s

tcc.o: tcc.c.o

.PHONY : tcc.o

# target to build an object file
tcc.c.o:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f bonobo/lib/bvm/src/tcc/CMakeFiles/tcc.dir/build.make bonobo/lib/bvm/src/tcc/CMakeFiles/tcc.dir/tcc.c.o
.PHONY : tcc.c.o

tcc.i: tcc.c.i

.PHONY : tcc.i

# target to preprocess a source file
tcc.c.i:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f bonobo/lib/bvm/src/tcc/CMakeFiles/tcc.dir/build.make bonobo/lib/bvm/src/tcc/CMakeFiles/tcc.dir/tcc.c.i
.PHONY : tcc.c.i

tcc.s: tcc.c.s

.PHONY : tcc.s

# target to generate assembly for a file
tcc.c.s:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f bonobo/lib/bvm/src/tcc/CMakeFiles/tcc.dir/build.make bonobo/lib/bvm/src/tcc/CMakeFiles/tcc.dir/tcc.c.s
.PHONY : tcc.c.s

win32/tools/tiny_libmaker.o: win32/tools/tiny_libmaker.c.o

.PHONY : win32/tools/tiny_libmaker.o

# target to build an object file
win32/tools/tiny_libmaker.c.o:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f bonobo/lib/bvm/src/tcc/CMakeFiles/tiny_libmaker.dir/build.make bonobo/lib/bvm/src/tcc/CMakeFiles/tiny_libmaker.dir/win32/tools/tiny_libmaker.c.o
.PHONY : win32/tools/tiny_libmaker.c.o

win32/tools/tiny_libmaker.i: win32/tools/tiny_libmaker.c.i

.PHONY : win32/tools/tiny_libmaker.i

# target to preprocess a source file
win32/tools/tiny_libmaker.c.i:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f bonobo/lib/bvm/src/tcc/CMakeFiles/tiny_libmaker.dir/build.make bonobo/lib/bvm/src/tcc/CMakeFiles/tiny_libmaker.dir/win32/tools/tiny_libmaker.c.i
.PHONY : win32/tools/tiny_libmaker.c.i

win32/tools/tiny_libmaker.s: win32/tools/tiny_libmaker.c.s

.PHONY : win32/tools/tiny_libmaker.s

# target to generate assembly for a file
win32/tools/tiny_libmaker.c.s:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(MAKE) -f bonobo/lib/bvm/src/tcc/CMakeFiles/tiny_libmaker.dir/build.make bonobo/lib/bvm/src/tcc/CMakeFiles/tiny_libmaker.dir/win32/tools/tiny_libmaker.c.s
.PHONY : win32/tools/tiny_libmaker.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... tcc"
	@echo "... install/local"
	@echo "... install"
	@echo "... edit_cache"
	@echo "... tiny_libmaker"
	@echo "... rebuild_cache"
	@echo "... package_source"
	@echo "... install/strip"
	@echo "... package"
	@echo "... libtcc1"
	@echo "... list_install_components"
	@echo "... libtcc"
	@echo "... libtcc.o"
	@echo "... libtcc.i"
	@echo "... libtcc.s"
	@echo "... tcc.o"
	@echo "... tcc.i"
	@echo "... tcc.s"
	@echo "... win32/tools/tiny_libmaker.o"
	@echo "... win32/tools/tiny_libmaker.i"
	@echo "... win32/tools/tiny_libmaker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/thosakwe/Source/Compilers/bonobo && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

